name: package-manager-publish-r
on:
  push:
    branches: [main]

jobs:
  package-manager-publish-r:
    name: package-manager-publish-r
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish to Package Manager
        uses: rstudio/actions/package-manager-publish-r@main
        with:
          url: http://packagemanager.example.com:4242
          api-token: ${{ secrets.PPM_API_TOKEN }}
          r-version: release
          distro: jammy
          source: local